# Generated by Django 5.0.1 on 2024-01-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='market.product'),
        ),
    ]
